modLoader="javafml"
loaderVersion="[4,)"
license="LGPL-3.0-only"
showAsResourcePack=false

[[mods]]
modId="weatheredwells"
version="${version}"
displayName="Weathered Wells"
description='''
A small exploration mod where collecting totems from weathered wells grants gentle healing effects near water.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/WeatheredWells"

[[mixins]]
config="weatheredwells.mixins.json"

[[dependencies.weatheredwells]]
modId="neoforge"
type="required"
versionRange="[21.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.weatheredwells]]
modId="minecraft"
type="required"
versionRange="[1.21.4]"
ordering="NONE"
side="BOTH"

[[dependencies.weatheredwells]]
modId="architectury"
type="required"
versionRange="[15.0.2,)"
ordering="AFTER"
side="BOTH"
