modLoader="javafml"
loaderVersion="[47,)"
license="LGPL-3.0-only"

[[mods]]
modId="weatheredwells"
version="${version}"
displayName="Weathered Wells"
description='''
A small exploration mod where collecting totems from weathered wells grants gentle healing effects near water.
'''
authors="ksoichiro"
displayURL="https://github.com/ksoichiro/WeatheredWells"

[[dependencies.weatheredwells]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.weatheredwells]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.weatheredwells]]
modId="architectury"
mandatory=true
versionRange="[9.2.14,)"
ordering="AFTER"
side="BOTH"
